name: Lint

on:
  push:
    paths:
      - 'delaynet/**.py'
      - 'tests/**.py'


jobs:
  run-black:
    name: Run Black codestyle
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Black
        uses: psf/black@stable
        with:
          src: './delaynet ./tests'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix code style issues with Black
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com

  run-pylint:
    strategy:
      matrix:
        python-version: ["3.12"]
    name: Run Pylint code analyzer
    needs: run-black
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pylint
        run: pip install pylint

      - name: Lint Source Code
        run: pylint -d E0401,W0511,R0917 delaynet/
        # ignore import-errors first, analyze later with tests in anaconda environment

      - name: Lint Tests
        run: pylint -d E0401,R0917 tests/